export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'; 
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT'; 
export const FETCH_ITEMS = 'FETCH_ITEMS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const FETCH_CART = 'FETCH_CART';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';